//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using CRA.ModelLayer.Core;

namespace CRA.AgroManagement {
    using System;
    using System.Collections;
    
    
    
    /// <summary>SoilLayerRainDataVarInfo contains the attributes for each variable in the domain class SoilLayer. Attributes are valorized via the static constructor. The data-type VarInfo causes  a dependency to the assembly CRA.Core.Preconditions.dll</summary>
	/// <remark>DCC - Domain Class Coder, http://www.isci.it/asp/asp2/utils.asp </remark>
    public class SoilLayerVarInfo : IVarInfoClass 
	{
        
        static  VarInfo _bulkDensity = new VarInfo();
        
        static  VarInfo _layerThickness = new VarInfo();
        
        static  VarInfo _fieldCapacityVolSWC = new VarInfo();
        
        static  VarInfo _wiltPointVolSWC = new VarInfo();
        
        static  VarInfo _soilWaterContentVol = new VarInfo();
        
        static  VarInfo _soilWaterPotential = new VarInfo();
        
        static SoilLayerVarInfo() 
        {
            DescribeVariables();
        }

        #region IVarInfoClass Members
        /// <summary>
        /// Soil layer attributes used in the component AgroManagement
        /// </summary>
        public string Description
        {
            get { return "Soil layer attributes used in the component AgroManagement."; }
        }

        /// <summary>
        /// Domain class of reference
        /// </summary>
        public string DomainClassOfReference
        {
            get { throw new Exception("CRA.AgroManagement.SoilLayer"); }
        }

        /// <summary>
        /// Description of the domain class on the knowledge base
        /// </summary>
        public string URL
        {
            get { throw new Exception("http://ontology.seamless-ip.org"); }
        }

        #endregion

        
        /// <summary>soil bulk density</summary>
        public static  VarInfo BulkDensity {
            get {
                return  _bulkDensity;
            }
        }
        
        /// <summary>soil layer thickness</summary>
        public static  VarInfo LayerThickness {
            get {
                return  _layerThickness;
            }
        }
        
        /// <summary>volumetric soil water content at field capacity</summary>
        public static  VarInfo FieldCapacityVolSWC {
            get {
                return  _fieldCapacityVolSWC;
            }
        }
        
        /// <summary>volumetric soil water content at permanent wilting point</summary>
        public static  VarInfo WiltPointVolSWC {
            get {
                return  _wiltPointVolSWC;
            }
        }
        
        /// <summary>volumetric soil water content</summary>
        public static  VarInfo SoilWaterContentVol {
            get {
                return  _soilWaterContentVol;
            }
        }
        
        /// <summary>soil water retention tension</summary>
        public static  VarInfo SoilWaterPotential {
            get {
                return  _soilWaterPotential;
            }
        }
        
        static void DescribeVariables() {
            //   
            _bulkDensity.Name = "bulkDensity";
            _bulkDensity.Description = "soil bulk density";
            _bulkDensity.MaxValue = 2;
            _bulkDensity.MinValue = 0.8;
            _bulkDensity.DefaultValue = 1.3;
            _bulkDensity.Units = "t/m3";
            //   
            _layerThickness.Name = "layerThickness";
            _layerThickness.Description = "soil layer thickness";
            _layerThickness.MaxValue = 2;
            _layerThickness.MinValue = 0.01;
            _layerThickness.DefaultValue = 0.1;
            _layerThickness.Units = "m";
            //   
            _fieldCapacityVolSWC.Name = "fieldCapacityVolSWC";
            _fieldCapacityVolSWC.Description = "volumetric soil water content at field capacity";
            _fieldCapacityVolSWC.MaxValue = 0.48;
            _fieldCapacityVolSWC.MinValue = 0.05;
            _fieldCapacityVolSWC.DefaultValue = 0.3;
            _fieldCapacityVolSWC.Units = "m3/m3";
            //   
            _wiltPointVolSWC.Name = "wiltPointVolSWC";
            _wiltPointVolSWC.Description = "volumetric soil water content at permanent wilting point";
            _wiltPointVolSWC.MaxValue = 0.3;
            _wiltPointVolSWC.MinValue = 0.01;
            _wiltPointVolSWC.DefaultValue = 0.15;
            _wiltPointVolSWC.Units = "m3/m3";
            //   
            _soilWaterContentVol.Name = "soilWaterContentVol";
            _soilWaterContentVol.Description = "volumetric soil water content";
            _soilWaterContentVol.MaxValue = 0.5;
            _soilWaterContentVol.MinValue = 0.01;
            _soilWaterContentVol.DefaultValue = 0.3;
            _soilWaterContentVol.Units = "m3/m3";
            //   
            _soilWaterPotential.Name = "soilWaterPotential";
            _soilWaterPotential.Description = "soil water retention tension";
            _soilWaterPotential.MaxValue = 0;
            _soilWaterPotential.MinValue = -1500;
            _soilWaterPotential.DefaultValue = 200;
            _soilWaterPotential.Units = "kPa";
        }

    }
}
